apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: heor
  labels:
    app: frontend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "us-central1-docker.pkg.dev/boxwood-sector-441703-p1/assignment/streamlit@sha256:691c1cdc536312a5192c847609c6160f540cfd2b2286423e635d3f3b14bbbb48"
          ports:
            - containerPort:80
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "200m"
            limits:
              memory: "0.5Gi"
              cpu: "200m"
      nodeSelector:
        type: application            
