apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-12-18T12:23:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: deployment-1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:allocateLoadBalancerNodePorts: {}
        f:externalTrafficPolicy: {}
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: unknown
    operation: Update
    time: "2024-12-18T12:23:33Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: cloud-controller-manager
    operation: Update
    subresource: status
    time: "2024-12-18T12:24:08Z"
  name: deployment-1-service
  namespace: default
  resourceVersion: "23186"
  uid: de541c58-7dd8-414a-9ac0-51f430d93478
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.235.215
  clusterIPs:
  - 34.118.235.215
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31889
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: deployment-1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.28.49.13
      ipMode: VIP
